PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>

# Get all MONDO terms with their ICD11 Foundation mappings

SELECT DISTINCT ?mondo_curie ?mondo_label ?icd11_xref
WHERE {
  ?mondo_term a owl:Class ;
              oboInOwl:hasDbXref ?icd11_xref ;
              rdfs:label ?mondo_label .
  
  FILTER(STRSTARTS(LCASE(STR(?icd11_xref)), "icd11"))
  
  BIND(REPLACE(STR(?mondo_term), "http://purl.obolibrary.org/obo/MONDO_", "MONDO:") AS ?mondo_curie)
}
ORDER BY ?mondo_curie

