PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>

SELECT ?mondo_curie ?mondo_term ?label ?xref
WHERE {
  ?mondo_term a owl:Class ;
              oboInOwl:hasDbXref ?xref ;
              rdfs:label ?label .
  BIND(REPLACE(STR(?mondo_term), "http://purl.obolibrary.org/obo/MONDO_", "MONDO:") AS ?mondo_curie)
}
ORDER BY ?mondo_term
